module.exports = [
  { name: 'Bench Press', muscleGroup: 'CHEST', equipment: 'barbell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Incline Dumbbell Press', muscleGroup: 'CHEST', equipment: 'dumbbell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Chest Fly', muscleGroup: 'CHEST', equipment: 'machine', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Cable Crossover', muscleGroup: 'CHEST', equipment: 'cable', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Push-Up', muscleGroup: 'CHEST', equipment: 'bodyweight', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Chest Press Machine', muscleGroup: 'CHEST', equipment: 'machine', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Pull-Up', muscleGroup: 'BACK', equipment: 'bodyweight', difficulty: 'advanced', videoUrl: '', description: '' },
  { name: 'Lat Pulldown', muscleGroup: 'BACK', equipment: 'cable', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Bent-Over Row', muscleGroup: 'BACK', equipment: 'barbell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Seated Cable Row', muscleGroup: 'BACK', equipment: 'cable', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Deadlift', muscleGroup: 'BACK', equipment: 'barbell', difficulty: 'advanced', videoUrl: '', description: '' },
  { name: 'Single-Arm Dumbbell Row', muscleGroup: 'BACK', equipment: 'dumbbell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Overhead Press', muscleGroup: 'SHOULDERS', equipment: 'barbell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Lateral Raise', muscleGroup: 'SHOULDERS', equipment: 'dumbbell', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Front Raise', muscleGroup: 'SHOULDERS', equipment: 'dumbbell', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Rear Delt Fly', muscleGroup: 'SHOULDERS', equipment: 'dumbbell', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Upright Row', muscleGroup: 'SHOULDERS', equipment: 'barbell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Shrugs', muscleGroup: 'SHOULDERS', equipment: 'dumbbell', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Barbell Curl', muscleGroup: 'BICEPS', equipment: 'barbell', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Dumbbell Curl', muscleGroup: 'BICEPS', equipment: 'dumbbell', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Hammer Curl', muscleGroup: 'BICEPS', equipment: 'dumbbell', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Preacher Curl', muscleGroup: 'BICEPS', equipment: 'machine', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Concentration Curl', muscleGroup: 'BICEPS', equipment: 'dumbbell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Cable Curl', muscleGroup: 'BICEPS', equipment: 'cable', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Triceps Pushdown', muscleGroup: 'TRICEPS', equipment: 'cable', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Overhead Triceps Extension', muscleGroup: 'TRICEPS', equipment: 'dumbbell', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Skullcrusher', muscleGroup: 'TRICEPS', equipment: 'barbell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Dips', muscleGroup: 'TRICEPS', equipment: 'bodyweight', difficulty: 'advanced', videoUrl: '', description: '' },
  { name: 'Close-Grip Bench Press', muscleGroup: 'TRICEPS', equipment: 'barbell', difficulty: 'advanced', videoUrl: '', description: '' },
  { name: 'Tricep Kickback', muscleGroup: 'TRICEPS', equipment: 'dumbbell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Back Squat', muscleGroup: 'QUADRICEPS', equipment: 'barbell', difficulty: 'advanced', videoUrl: '', description: '' },
  { name: 'Leg Press', muscleGroup: 'QUADRICEPS', equipment: 'machine', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Lunge', muscleGroup: 'QUADRICEPS', equipment: 'bodyweight', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Leg Extension', muscleGroup: 'QUADRICEPS', equipment: 'machine', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Step-Up', muscleGroup: 'QUADRICEPS', equipment: 'bodyweight', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Bulgarian Split Squat', muscleGroup: 'QUADRICEPS', equipment: 'dumbbell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Romanian Deadlift', muscleGroup: 'GLUTES_HAMSTRINGS', equipment: 'barbell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Leg Curl', muscleGroup: 'GLUTES_HAMSTRINGS', equipment: 'machine', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Hip Thrust', muscleGroup: 'GLUTES_HAMSTRINGS', equipment: 'barbell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Glute Bridge', muscleGroup: 'GLUTES_HAMSTRINGS', equipment: 'bodyweight', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Good Morning', muscleGroup: 'GLUTES_HAMSTRINGS', equipment: 'barbell', difficulty: 'advanced', videoUrl: '', description: '' },
  { name: 'Kettlebell Swing', muscleGroup: 'GLUTES_HAMSTRINGS', equipment: 'kettlebell', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Standing Calf Raise', muscleGroup: 'CALVES', equipment: 'machine', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Seated Calf Raise', muscleGroup: 'CALVES', equipment: 'machine', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Leg Press Calf Raise', muscleGroup: 'CALVES', equipment: 'machine', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Donkey Calf Raise', muscleGroup: 'CALVES', equipment: 'machine', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Single-Leg Calf Raise', muscleGroup: 'CALVES', equipment: 'bodyweight', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Jump Rope', muscleGroup: 'CALVES', equipment: 'rope', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Crunches', muscleGroup: 'ABS', equipment: 'bodyweight', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Plank', muscleGroup: 'ABS', equipment: 'bodyweight', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Hanging Leg Raise', muscleGroup: 'ABS', equipment: 'bodyweight', difficulty: 'advanced', videoUrl: '', description: '' },
  { name: 'Russian Twist', muscleGroup: 'ABS', equipment: 'bodyweight', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Cable Crunch', muscleGroup: 'ABS', equipment: 'cable', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Bicycle Crunch', muscleGroup: 'ABS', equipment: 'bodyweight', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Running', muscleGroup: 'OTHER', equipment: 'none', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Cycling', muscleGroup: 'OTHER', equipment: 'machine', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Rowing', muscleGroup: 'OTHER', equipment: 'machine', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Jumping Jacks', muscleGroup: 'OTHER', equipment: 'bodyweight', difficulty: 'beginner', videoUrl: '', description: '' },
  { name: 'Burpees', muscleGroup: 'OTHER', equipment: 'bodyweight', difficulty: 'intermediate', videoUrl: '', description: '' },
  { name: 'Swimming', muscleGroup: 'OTHER', equipment: 'bodyweight', difficulty: 'intermediate', videoUrl: '', description: '' }
];
